name: Build and test PR

on:
  pull_request:
    branches: ["dev"]
    paths-ignore:
      - README.md
      - LICENSE

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Try build and Test
        run: |
          export TEST_IMAGE_NAME=${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker compose --file docker-compose.test.yml up --exit-code-from sut -t 10 --build

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Try build multi-arch
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: ${{ vars.CONTAINER_ARCH }}
          provenance: false

      - name: Run Trivy vulnerability scanner for PR
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: 0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db

      - name: Run the Anchore scan action for PR
        uses: anchore/scan-action@v6
        id: anchore-scan-pr
        with:
          image: 'docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          output-format: table
          fail-build: false
